### ISSUE TITLE
Variable as slider

### ISSUE THREAD

**Issue by saVantCZ** [ashpynov/ThemeOptions#5]
Is it possible to add slider for variable?

For example mediaelement is using Double value for volume from 0 to 1 and would be cool to have it as slider and be able to set custom range and steps. For example min 0 max 1 steps 0.1 

Another example where slider can be used is for animations duration (if TimeSpan constant would be available) to slow down or make animations faster.

**Comment by ashpynov** [comment]
Implemented for:
- Double, Int32, Duration, TimeSpan

### Slider customization
As soon as Slider more complex control to specify Double, Int32, Duration or TimeSpan It is require some additional specification in Variables.
Thus it is require to specify:
- Min - minimum value
- Max - maximum value
- Step - step of values, amount of minimal changes by Left/Right
- SmallChange (optional) - same as step either Step or Small change had to be defined.
- LargeChange (optional) - amount of big change by PageUp/Down or LB/RB, by default it will try to calculate automatically as 1/10 of range.

Value/format of this parameters had to corresponds to specified type:

```yaml
SampleDoubleValue:
    Title: Double value Sample
    Type: Double
    Default: 0.5
    Slider:
        Min: 0
        Max: 2
        Step: 0.1
```
```yaml
SampleDurationValue:
    Title: Duration value Sample
    Type: Duration
    Default: "00:00:00.5"
    Slider:
        Min: "00:00:00.1"
        Max: "00:01:00"
        Step: "00.1"
        LargeChange: "00:00:01"
```
```yaml
SampleInt32Value:
    Title: Int value Sample
    Type: Int32
    Default: 5
    Slider:
        Min: 0
        Max: 10
        Step: 1
```
